# GitHub Secret Scanning Configuration
# This file excludes test directories from secret scanning to avoid false positives
# Test scripts intentionally contain example credentials and security violations for testing purposes

paths-ignore:
  - 'tests/**'
  - '**/TestScripts/**'
  - '**/*test*.ps1'
  - '**/*Test*.ps1'
