# PowerShield Configuration
version: "1.0"

# Analysis Settings
analysis:
  severity_threshold: "Medium"
  max_file_size: 10485760  # 10MB
  timeout_seconds: 30
  parallel_analysis: false  # Disable to avoid the "Using variable" errors
  
  # Path exclusions (glob patterns)
  exclude_paths:
    - "tests/**"          # Exclude all test files
    - "**/TestScripts/**" # Exclude specific test script directories
    - "**/*.Tests.ps1"    # Exclude Pester test files
    - "**/*.tests.ps1"    # Exclude lowercase test files
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/*.min.ps1"
    - ".github/**"
    - "rules/community/**" # Exclude community rules that have issues

# Rule Configuration
rules:
  # Core security rules
  InsecureHashAlgorithms:
    enabled: true
    severity: "High"
  
  CredentialExposure:
    enabled: true
    severity: "Critical"
  
  CommandInjection:
    enabled: true
    severity: "Critical"
  
  CertificateValidation:
    enabled: true
    severity: "High"

# Auto-Fix Configuration
autofix:
  enabled: true
  provider: "github-models"
  model: "gpt-4o-mini"
  confidence_threshold: 0.8
  
  # Rule-specific fix settings
  rule_fixes:
    InsecureHashAlgorithms: true
    CredentialExposure: true
    CommandInjection: false  # Too risky to auto-fix
    CertificateValidation: false  # Requires manual review

# CI/CD Integration
ci:
  fail_on: ["Critical", "High"]
  generate_sarif: true
  upload_artifacts: true

# Hooks Configuration
hooks:
  enabled: true
  block_on: ["Critical", "High"]